name: Deploy to EC2
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build and push Docker image
        run: |
          docker build -t node-app .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag node-app ${{ secrets.DOCKER_REPO_URL }}:node-app
          docker push ${{ secrets.DOCKER_REPO_URL }}:node-app

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO_URL }}:node-app
            sudo docker stop node-app-server || true
            sudo docker rm node-app-server || true
            sudo docker run -d -p 3000:3000 --name node-app-server ${{ secrets.DOCKER_REPO_URL }}:node-app